spring:
  application:
    name: exam-person
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.53.223.77:3306/chaoxing_exam_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: chenguoqing

mybatis-plus:
  mapper-locations: classpath:com/shui/exam/mapper/xml/*.xml
#
#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  secret: mall-admin-secret #JWT加解密使用的密钥
#  expiration: 604800 #JWT的超期限时间(60*60*24*7)
#  tokenHead: 'Bearer '  #JWT负载中拿到开头

#redis:
#  database: mall
#  key:
#    admin: 'ums:admin'
#    resourceList: 'ums:resourceList'
#  expire:
#    common: 86400 # 24小时


aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tEa1JzBX3JRHEN86LdH
    accessKeySecret: lCfZce5vOfOoDRka3TFkXXIZMM9VJr
    bucketName: chaoxing-exam

server:
  port: 8110
